[package]
name = "tensorloom-core"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.39.6"
serde = { version = "1", features = ["derive"] }
burn = { version = "0.21.0", features = ["wgpu", "ndarray", "autodiff", "train"] }
burn-wgpu = "0.21.0"
thiserror = "2.0.21"
wgpu = "30.0.1"
pollster = "1.0.1"
protobuf = "=3.4.0"
